server.port=8080

spring.application.name=products-api

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

spring.output.ansi.enabled=ALWAYS

logging.level.com.example.products=INFO
logging.level.org.springframework.web=INFO
